In [441]:
import numpy as np
import pandas as pd
import sklearn

In [442]:
df1 = pd.read_csv('spam.csv', encoding='latin1')
df1

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [443]:
df1.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1, inplace=True)
df1

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [444]:
df1['v2'] = df1['v2'].str.lower()
df1

        v1                                                 v2
0      ham  go until jurong point, crazy.. available only ...
1      ham                      ok lar... joking wif u oni...
2     spam  free entry in 2 a wkly comp to win fa cup fina...
3      ham  u dun say so early hor... u c already then say...
4      ham  nah i don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  this is the 2nd time we have tried 2 contact u...
5568   ham              will ì_ b going to esplanade fr home?
5569   ham  pity, * was in mood for that. so...any other s...
5570   ham  the guy did some bitching but i acted like i'd...
5571   ham                         rofl. its true to its name

[5572 rows x 2 columns]

In [445]:
import re
df1['v2'] = df1['v2'].apply(lambda x: re.sub(r'[^a-zA-Z\s]', '', x))
df1['v2'] = df1['v2'].apply(lambda x: re.sub(r'\d+', '', x))
df1

        v1                                                 v2
0      ham  go until jurong point crazy available only in ...
1      ham                            ok lar joking wif u oni
2     spam  free entry in  a wkly comp to win fa cup final...
3      ham        u dun say so early hor u c already then say
4      ham  nah i dont think he goes to usf he lives aroun...
...    ...                                                ...
5567  spam  this is the nd time we have tried  contact u u...
5568   ham                 will  b going to esplanade fr home
5569   ham  pity  was in mood for that soany other suggest...
5570   ham  the guy did some bitching but i acted like id ...
5571   ham                          rofl its true to its name

[5572 rows x 2 columns]

In [446]:
df1['v1'] = df1.v1.map({'spam':0, 'ham':1})
df1

      v1                                                 v2
0      1  go until jurong point crazy available only in ...
1      1                            ok lar joking wif u oni
2      0  free entry in  a wkly comp to win fa cup final...
3      1        u dun say so early hor u c already then say
4      1  nah i dont think he goes to usf he lives aroun...
...   ..                                                ...
5567   0  this is the nd time we have tried  contact u u...
5568   1                 will  b going to esplanade fr home
5569   1  pity  was in mood for that soany other suggest...
5570   1  the guy did some bitching but i acted like id ...
5571   1                          rofl its true to its name

[5572 rows x 2 columns]

In [447]:
X = df1['v2'].values
y = df1['v1'].values
y = y.astype('int')

In [448]:
print("X")
print(X)
print("y")
print(y)

X
['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat'
 'ok lar joking wif u oni'
 'free entry in  a wkly comp to win fa cup final tkts st may  text fa to  to receive entry questionstd txt ratetcs apply overs'
 ... 'pity  was in mood for that soany other suggestions'
 'the guy did some bitching but i acted like id be interested in buying something else next week and he gave it to us for free'
 'rofl its true to its name']
y
[1 1 0 ... 1 1 1]

In [449]:
from sklearn.feature_extraction.text import CountVectorizer 
vec = CountVectorizer()

In [450]:
vec.fit(X)
vec.vocabulary_

{'go': 2846,
 'until': 7756,
 'jurong': 3740,
 'point': 5490,
 'crazy': 1557,
 'available': 489,
 'only': 5076,
 'in': 3457,
 'bugis': 944,
 'great': 2942,
 'world': 8254,
 'la': 3893,
 'buffet': 942,
 'cine': 1274,
 'there': 7329,
 'got': 2903,
 'amore': 247,
 'wat': 8003,
 'ok': 5036,
 'lar': 3929,
 'joking': 3708,
 'wif': 8144,
 'oni': 5070,
 'free': 2635,
 'entry': 2219,
 'wkly': 8205,
 'comp': 1390,
 'to': 7457,
 'win': 8159,
 'fa': 2355,
 'cup': 1614,
 'final': 2481,
 'tkts': 7446,
 'st': 6840,
 'may': 4373,
 'text': 7272,
 'receive': 5893,
 'questionstd': 5784,
 'txt': 7655,
 'ratetcs': 5837,
 'apply': 339,
 'overs': 5178,
 'dun': 2070,
 'say': 6242,
 'so': 6659,
 'early': 2092,
 'hor': 3279,
 'already': 220,
 'then': 7324,
 'nah': 4734,
 'dont': 1979,
 'think': 7353,
 'he': 3100,
 'goes': 2859,
 'usf': 7806,
 'lives': 4096,
 'around': 390,
 'here': 3155,
 'though': 7376,
 'freemsg': 2643,
 'hey': 3174,
 'darling': 1677,
 'its': 3613,
 'been': 648,
 'weeks': 8059,
 'now': 4931,
 'and': 264,
 'no': 4869,
 'word': 8240,
 'back': 533,
 'id': 3398,
 'like': 4046,
 'some': 6675,
 'fun': 2707,
 'you': 8451,
 'up': 7759,
 'for': 2585,
 'it': 3594,
 'still': 6911,
 'tb': 7199,
 'xxx': 8383,
 'std': 6886,
 'chgs': 1219,
 'send': 6336,
 'rcv': 5849,
 'even': 2266,
 'my': 4720,
 'brother': 911,
 'is': 3582,
 'not': 4914,
 'speak': 6755,
 'with': 8190,
 'me': 4383,
 'they': 7343,
 'treat': 7581,
 'aids': 165,
 'patent': 5278,
 'as': 408,
 'per': 5322,
 'your': 8468,
 'request': 6004,
 'melle': 4419,
 'oru': 5138,
 'minnaminunginte': 4502,
 'nurungu': 4966,
 'vettam': 7871,
 'has': 3079,
 'set': 6366,
 'callertune': 1014,
 'all': 204,
 'callers': 1013,
 'press': 5620,
 'copy': 1496,
 'friends': 2667,
 'winner': 8171,
 'valued': 7840,
 'network': 4809,
 'customer': 1626,
 'have': 3091,
 'selected': 6322,
 'receivea': 5894,
 'prize': 5654,
 'reward': 6063,
 'claim': 1280,
 'call': 1005,
 'code': 1341,
 'kl': 3854,
 'valid': 7836,
 'hours': 3298,
 'had': 3019,
 'mobile': 4562,
 'months': 4607,
 'or': 5115,
 'more': 4614,
 'entitled': 2216,
 'update': 7763,
 'the': 7309,
 'latest': 3946,
 'colour': 1364,
 'mobiles': 4563,
 'camera': 1040,
 'co': 1330,
 'on': 5061,
 'im': 3429,
 'gonna': 2876,
 'be': 624,
 'home': 3246,
 'soon': 6705,
 'want': 7982,
 'talk': 7165,
 'about': 18,
 'this': 7361,
 'stuff': 6986,
 'anymore': 305,
 'tonight': 7504,
 'ive': 3623,
 'cried': 1575,
 'enough': 2207,
 'today': 7464,
 'six': 6556,
 'chances': 1157,
 'cash': 1100,
 'from': 2685,
 'pounds': 5555,
 'csh': 1593,
 'cost': 1509,
 'pday': 5303,
 'days': 1703,
 'tsandcs': 7616,
 'reply': 5996,
 'hl': 3213,
 'info': 3492,
 'urgent': 7785,
 'won': 8224,
 'week': 8054,
 'membership': 4425,
 'our': 5150,
 'jackpot': 3632,
 'tc': 7201,
 'wwwdbuknet': 8329,
 'lccltd': 3965,
 'pobox': 5473,
 'ldnwarw': 3967,
 'searching': 6289,
 'right': 6075,
 'words': 8243,
 'thank': 7291,
 'breather': 880,
 'promise': 5693,
 'wont': 8231,
 'take': 7156,
 'help': 3143,
 'granted': 2931,
 'will': 8156,
 'fulfil': 2703,
 'wonderful': 8228,
 'blessing': 761,
 'at': 443,
 'times': 7422,
 'date': 1686,
 'sunday': 7053,
 'xxxmobilemovieclub': 8384,
 'use': 7800,
 'credit': 1565,
 'click': 1302,
 'wap': 7987,
 'link': 4069,
 'next': 4827,
 'message': 4450,
 'httpwap': 3327,
 'xxxmobilemovieclubcomnqjkgighjjgcbl': 8385,
 'oh': 5029,
 'kim': 3821,
 'watching': 8008,
 'eh': 2141,
 'remember': 5963,
 'how': 3305,
 'spell': 6771,
 'his': 3201,
 'name': 4740,
 'yes': 8424,
 'did': 1853,
 'naughty': 4764,
 'make': 4289,
 'wet': 8097,
 'fine': 2489,
 'if': 3411,
 'thats': 7306,
 'way': 8020,
 'feel': 2432,
 'gota': 2904,
 'england': 2198,
 'macedonia': 4252,
 'miss': 4522,
 'goalsteam': 2850,
 'news': 4822,
 'ur': 7782,
 'national': 4757,
 'team': 7217,
 'eg': 2133,
 'trywales': 7614,
 'scotland': 6268,
 'poboxoxwwq': 5478,
 'that': 7299,
 'seriously': 6359,
 'going': 2864,
 'try': 7611,
 'ha': 3015,
 'pay': 5291,
 'first': 2509,
 'when': 8109,
 'da': 1642,
 'stock': 6915,
 'comin': 1380,
 'aft': 126,
 'finish': 2495,
 'lunch': 4227,
 'str': 6944,
 'down': 2000,
 'lor': 4153,
 'ard': 366,
 'smth': 6642,
 'ffffffffff': 2450,
 'alright': 222,
 'can': 1045,
 'meet': 4404,
 'sooner': 6707,
 'just': 3742,
 'forced': 2587,
 'myself': 4725,
 'eat': 2105,
 'slice': 6592,
 'really': 5874,
 'hungry': 3355,
 'tho': 7371,
 'sucks': 7025,
 'mark': 4326,
 'getting': 2803,
 'worried': 8260,
 'knows': 3865,
 'sick': 6499,
 'turn': 7637,
 'pizza': 5415,
 'lol': 4130,
 'always': 232,
 'convincing': 1482,
 'catch': 1112,
 'bus': 964,
 'are': 367,
 'frying': 2691,
 'an': 259,
 'egg': 2136,
 'tea': 7211,
 'eating': 2108,
 'moms': 4586,
 'left': 3988,
 'over': 5172,
 'dinner': 1885,
 'do': 1936,
 'love': 4178,
 'amp': 249,
 'were': 8085,
 'packing': 5201,
 'car': 1067,
 'ill': 3425,
 'let': 4013,
 'know': 3861,
 'theres': 7334,
 'room': 6119,
 'ahhh': 156,
 'work': 8246,
 'vaguely': 7831,
 'what': 8102,
 'does': 1949,
 'wait': 7953,
 'clear': 1296,
 'sure': 7081,
 'being': 668,
 'sarcastic': 6220,
 'why': 8137,
 'doesnt': 1951,
 'live': 4092,
 'us': 7796,
 'yeah': 8411,
 'was': 7997,
 'apologetic': 326,
 'fallen': 2382,
 'out': 5153,
 'she': 6414,
 'actin': 64,
 'spoilt': 6799,
 'child': 1235,
 'caught': 1116,
 'till': 7417,
 'but': 971,
 'we': 8027,
 'doing': 1962,
 'too': 7510,
 'badly': 539,
 'cheers': 1201,
 'tell': 7236,
 'anything': 311,
 'fear': 2424,
 'of': 5002,
 'fainting': 2372,
 'housework': 3303,
 'quick': 5785,
 'cuppa': 1616,
 'thanks': 7292,
 'subscription': 7013,
 'ringtone': 6084,
 'uk': 7686,
 'charged': 1169,
 'month': 4603,
 'please': 5444,
 'confirm': 1437,
 'by': 986,
 'replying': 5998,
 'yup': 8494,
 'look': 4141,
 'timings': 7429,
 'msg': 4660,
 'again': 134,
 'xuhui': 8379,
 'learn': 3977,
 'nd': 4770,
 'her': 3154,
 'lesson': 4011,
 'am': 234,
 'oops': 5089,
 'roommates': 6122,
 'done': 1976,
 'see': 6306,
 'letter': 4015,
 'decide': 1741,
 'hello': 3136,
 'hows': 3311,
 'saturday': 6234,
 'texting': 7279,
 'youd': 8455,
 'decided': 1742,
 'tomo': 7489,
 'trying': 7613,
 'invite': 3557,
 'pls': 5452,
 'ahead': 154,
 'watts': 8017,
 'wanted': 7984,
 'weekend': 8056,
 'abiola': 14,
 'forget': 2593,
 'need': 4783,
 'crave': 1554,
 'most': 4628,
 'sweet': 7111,
 'arabian': 363,
 'steed': 6893,
 'mmmmmm': 4552,
 'yummy': 8489,
 'rodger': 6108,
 'burns': 961,
 'tried': 7590,
 're': 5853,
 'sms': 6637,
 'nokia': 4885,
 'camcorder': 1038,
 'delivery': 1780,
 'tomorrow': 7492,
 'who': 8130,
 'seeing': 6308,
 'hope': 3270,
 'man': 4299,
 'well': 8073,
 'endowed': 2188,
 'ltgt': 4212,
 'inches': 3460,
 'callsmessagesmissed': 1030,
 'calls': 1029,
 'didnt': 1855,
 'get': 2794,
 'hep': 3153,
 'immunisation': 3441,
 'nigeria': 4840,
 'fair': 2373,
 'hopefully': 3274,
 'tyler': 7666,
 'cant': 1058,
 'could': 1521,
 'maybe': 4375,
 'ask': 419,
 'bit': 735,
 'stubborn': 6975,
 'hospital': 3286,
 'kept': 3792,
 'telling': 7237,
 'weak': 8028,
 'sucker': 7023,
 'hospitals': 3287,
 'suckers': 7024,
 'thinked': 7354,
 'time': 7419,
 'saw': 6241,
 'class': 1288,
 'gram': 2923,
 'usually': 7817,
 'runs': 6165,
 'half': 3033,
 'eighth': 2144,
 'smarter': 6615,
 'gets': 2799,
 'almost': 216,
 'whole': 8131,
 'second': 6293,
 'fyi': 2723,
 'ride': 6074,
 'morning': 4618,
 'hes': 3169,
 'crashing': 1553,
 'place': 5417,
 'wow': 8279,
 'never': 4813,
 'realized': 5872,
 'embarassed': 2169,
 'accomodations': 44,
 'thought': 7377,
 'liked': 4047,
 'since': 6526,
 'best': 688,
 'seemed': 6312,
 'happy': 3068,
 'cave': 1120,
 'sorry': 6717,
 'give': 2827,
 'offered': 5009,
 'embarassing': 2170,
 'ac': 30,
 'sptv': 6822,
 'new': 4817,
 'jersey': 3675,
 'devils': 1833,
 'detroit': 1827,
 'red': 5917,
 'wings': 8169,
 'play': 5433,
 'ice': 3393,
 'hockey': 3230,
 'correct': 1501,
 'incorrect': 3471,
 'end': 2184,
 'mallika': 4298,
 'sherawat': 6421,
 'yesterday': 8434,
 'find': 2486,
 'lturlgt': 4216,
 'congrats': 1444,
 'year': 8413,
 'special': 6757,
 'cinema': 1275,
 'pass': 5266,
 'yours': 8472,
 'suprman': 7079,
 'matrix': 4361,
 'starwars': 6872,
 'etc': 2252,
 'bxipwe': 985,
 'pm': 5461,
 'later': 3944,
 'meeting': 4407,
 'where': 8115,
 'reached': 5856,
 'yesgauti': 8427,
 'sehwag': 6319,
 'odi': 5001,
 'series': 6357,
 'pick': 5385,
 'burger': 956,
 'yourself': 8473,
 'move': 4642,
 'pain': 5208,
 'killing': 3818,
 'good': 2878,
 'joke': 3703,
 'girls': 2824,
 'situation': 6552,
 'seekers': 6309,
 'part': 5253,
 'checking': 1195,
 'iq': 3571,
 'took': 7511,
 'forever': 2590,
 'come': 1372,
 'double': 1992,
 'check': 1191,
 'hair': 3028,
 'dresser': 2027,
 'said': 6187,
 'wun': 8315,
 'cut': 1630,
 'short': 6461,
 'nice': 4833,
 'pleased': 5445,
 'advise': 108,
 'following': 2568,
 'recent': 5897,
 'review': 6061,
 'mob': 4560,
 'awarded': 508,
 'bonus': 804,
 'song': 6699,
 'dedicated': 1752,
 'day': 1698,
 'which': 8123,
 'dedicate': 1751,
 'valuable': 7838,
 'frnds': 2676,
 'rply': 6139,
 'complimentary': 1409,
 'trip': 7591,
 'eurodisinc': 2258,
 'trav': 7573,
 'acoentry': 59,
 'dis': 1898,
 'morefrmmob': 4615,
 'shracomorsglsuplt': 6485,
 'ls': 4202,
 'aj': 176,
 'hear': 3112,
 'divorce': 1927,
 'barbie': 572,
 'comes': 1376,
 'kens': 3790,
 'plane': 5424,
 'wah': 7946,
 'lucky': 4220,
 'save': 6237,
 'money': 4591,
 'hee': 3128,
 'finished': 2497,
 'hi': 3179,
 'babe': 522,
 'wanna': 7980,
 'something': 6685,
 'xx': 8380,
 'kkwhere': 3851,
 'youhow': 8458,
 'performed': 5329,
 'waiting': 7957,
 'machan': 4254,
 'once': 5064,
 'cool': 1488,
 'gentleman': 2785,
 'dignity': 1875,
 'respect': 6025,
 'peoples': 5321,
 'very': 7870,
 'much': 4679,
 'shy': 6494,
 'pa': 5196,
 'operate': 5096,
 'after': 127,
 'same': 6204,
 'looking': 4145,
 'job': 3690,
 'tas': 7183,
 'earn': 2093,
 'ah': 152,
 'stop': 6925,
 'urgnt': 7789,
 'real': 5866,
 'yo': 8445,
 'tickets': 7408,
 'one': 5066,
 'jacket': 3631,
 'used': 7801,
 'multis': 4690,
 'started': 6865,
 'requests': 6005,
 'came': 1039,
 'bed': 642,
 'coins': 1348,
 'factory': 2363,
 'gotta': 2909,
 'nitros': 4864,
 'ela': 2149,
 'kanoil': 3766,
 'download': 2001,
 'wen': 8079,
 'stand': 6853,
 'close': 1309,
 'youll': 8462,
 'another': 288,
 'night': 4842,
 'spent': 6776,
 'late': 3939,
 'afternoon': 129,
 'casualty': 1110,
 'means': 4390,
 'havent': 3093,
 'any': 301,
 'stuffmoro': 6990,
 'includes': 3464,
 'sheets': 6416,
 'smile': 6624,
 'pleasure': 5447,
 'trouble': 7597,
 'pours': 5557,
 'rain': 5809,
 'sum': 7045,
 'hurts': 3369,
 'becoz': 640,
 'someone': 6678,
 'loves': 4188,
 'smiling': 6628,
 'service': 6362,
 'representative': 6002,
 'between': 697,
 'ampm': 251,
 'guaranteed': 2983,
 'planning': 5429,
 'buy': 976,
 'lido': 4028,
 'show': 6476,
 'collected': 1357,
 'simply': 6523,
 'password': 5274,
 'mix': 4542,
 'verify': 7866,
 'usher': 7808,
 'britney': 901,
 'fml': 2558,
 'telugu': 7242,
 'moviewat': 4647,
 'abt': 25,
 'loads': 4107,
 'loans': 4109,
 'wk': 8201,
 'hols': 3244,
 'run': 6162,
 'forgot': 2598,
 'hairdressers': 3030,
 'appointment': 342,
 'four': 2616,
 'shower': 6478,
 'beforehand': 656,
 'cause': 1117,
 'prob': 5660,
 'ham': 3039,
 'nothing': 4919,
 'else': 2163,
 'okay': 5037,
 'price': 5633,
 'long': 4137,
 'legal': 3991,
 'them': 7317,
 'ave': 495,
 'ams': 254,
 'gone': 2873,
 'driving': 2036,
 'test': 7266,
 'yet': 8435,
 'youre': 8469,
 'mean': 4386,
 'guess': 2991,
 'gave': 2756,
 'boston': 826,
 'men': 4430,
 'changed': 1159,
 'search': 6288,
 'location': 4112,
 'nyc': 4976,
 'cuz': 1637,
 'signin': 6511,
 'page': 5204,
 'says': 6246,
 'umma': 7695,
 'life': 4031,
 'vava': 7852,
 'lot': 4163,
 'dear': 1723,
 'wishes': 8184,
 'birthday': 733,
 'making': 4293,
 'truly': 7605,
 'memorable': 4427,
 'aight': 167,
 'hit': 3204,
 'would': 8275,
 'ip': 3565,
 'address': 83,
 'considering': 1455,
 'computer': 1416,
 'isnt': 3591,
 'minecraft': 4497,
 'server': 6361,
 'grumpy': 2975,
 'old': 5054,
 'people': 5320,
 'mom': 4583,
 'better': 695,
 'lying': 4243,
 'jokes': 3705,
 'worry': 8263,
 'busy': 969,
 'plural': 5457,
 'noun': 4928,
 'research': 6011,
 'dinnermsg': 1886,
 'cos': 1507,
 'things': 7352,
 'scared': 6253,
 'mah': 4276,
 'loud': 4173,
 'gent': 2783,
 'contact': 1460,
 'last': 3936,
 'weekends': 8057,
 'draw': 2015,
 'shows': 6484,
 'hrs': 3318,
 'ppm': 5565,
 'wa': 7942,
 'openin': 5093,
 'sentence': 6349,
 'formal': 2601,
 'anyway': 315,
 'juz': 3746,
 'tt': 7622,
 'eatin': 2107,
 'puttin': 5761,
 'weighthaha': 8064,
 'anythin': 310,
 'happened': 3060,
 'entered': 2209,
 'cabin': 991,
 'bday': 623,
 'boss': 825,
 'felt': 2441,
 'askd': 420,
 'invited': 3558,
 'apartment': 320,
 'went': 8082,
 'specially': 6762,
 'holiday': 3240,
 'flights': 2535,
 'inc': 3458,
 'operator': 5097,
 'pmin': 5463,
 'goodo': 2892,
 'must': 4710,
 'friday': 2660,
 'eggpotato': 2137,
 'ratio': 5839,
 'tortilla': 7530,
 'needed': 4785,
 'hmmmy': 3226,
 'uncle': 7703,
 'informed': 3496,
 'paying': 5296,
 'school': 6259,
 'directly': 1892,
 'food': 2575,
 'private': 5651,
 'account': 48,
 'statement': 6875,
 'unredeemed': 7747,
 'points': 5491,
 'identifier': 3405,
 'expires': 2334,
 'caller': 1012,
 'landline': 3916,
 'boxwrc': 848,
 'applespairsall': 337,
 'malarky': 4295,
 'todays': 7470,
 'voda': 7920,
 'numbers': 4962,
 'ending': 2186,
 'award': 507,
 'match': 4349,
 'quoting': 5797,
 'standard': 6854,
 'rates': 5836,
 'app': 330,
 'sao': 6214,
 'mu': 4678,
 'predict': 5595,
 'll': 4100,
 'buying': 979,
 'knowyetunde': 3868,
 'hasnt': 3081,
 'sent': 6347,
 'bother': 829,
 'sending': 6339,
 'involve': 3562,
 'shouldnt': 6471,
 'imposed': 3447,
 'apologise': 327,
 'girl': 2820,
 'del': 1770,
 'bak': 548,
 'lucyxx': 4224,
 'kkhow': 3845,
 'tmorrowpls': 7451,
 'accomodate': 43,
 'answer': 291,
 'question': 5781,
 'sunshine': 7060,
 'quiz': 5792,
 'top': 7520,
 'sony': 6702,
 'dvd': 2080,
 'player': 5435,
 'country': 1527,
 'algarve': 196,
 'ansr': 290,
 'sptyrone': 6823,
 'laid': 3907,
 'dogging': 1956,
 'locations': 4113,
 'direct': 1891,
 'join': 3698,
 'uks': 7689,
 'largest': 3933,
 'bt': 927,
 'txting': 7660,
 'gravel': 2936,
 'nt': 4950,
 'eca': 2110,
 'pmsgp': 5466,
 'haf': 3022,
 'msn': 4671,
 'yijuehotmailcom': 8442,
 'him': 3193,
 'rooms': 6123,
 'befor': 654,
 'activities': 70,
 'msgs': 4664,
 'chat': 1181,
 'svc': 7097,
 'hardcore': 3070,
 'services': 6363,
 'age': 139,
 'yr': 8484,
 'lazy': 3963,
 'type': 7668,
 'lect': 3985,
 'pouch': 5552,
 'sir': 6538,
 'mail': 4280,
 'swt': 7126,
 'nver': 4971,
 'tired': 7432,
 'little': 4091,
 'lovable': 4177,
 'persons': 5347,
 'cozsomtimes': 1541,
 'those': 7372,
 'occupy': 4993,
 'biggest': 714,
 'their': 7314,
 'hearts': 3120,
 'gud': 2985,
 'ni': 4831,
 'open': 5090,
 'ya': 8395,
 'dot': 1991,
 'whats': 8104,
 'staff': 6844,
 'taking': 7162,
 'replied': 5994,
 'randy': 5829,
 'sexy': 6379,
 'female': 2442,
 'local': 4111,
 'luv': 4233,
 'netcollex': 4805,
 'ltd': 4207,
 'ummmawill': 7696,
 'inour': 3513,
 'begin': 661,
 'qatar': 5768,
 'pray': 5587,
 'hard': 3069,
 'ki': 3806,
 'deleted': 1774,
 'sindu': 6528,
 'birla': 729,
 'soft': 6665,
 'wine': 8167,
 'flowing': 2549,
 'nevering': 4814,
 'thk': 7363,
 'plaza': 5442,
 'typical': 7671,
 'everywhere': 2284,
 'dirt': 1895,
 'floor': 2543,
 'windows': 8164,
 'shirt': 6435,
 'sometimes': 6689,
 'mouth': 4641,
 'dream': 2019,
 'without': 8194,
 'chores': 1261,
 'joy': 3720,
 'lots': 4166,
 'tv': 7642,
 'exist': 2317,
 'hail': 3027,
 'mist': 4533,
 'become': 638,
 'aaooooright': 3,
 'leaving': 3984,
 'house': 3299,
 'interview': 3543,
 'boy': 849,
 'meare': 4393,
 'missing': 4526,
 'annoncement': 281,
 'years': 8414,
 'arrange': 394,
 'keep': 3784,
 'safe': 6182,
 'because': 636,
 'envy': 2223,
 'everyone': 2278,
 'sees': 6316,
 'parentsi': 5244,
 'hand': 3042,
 'excited': 2305,
 'each': 2086,
 'spend': 6774,
 'bootydelious': 817,
 'inviting': 3559,
 'friend': 2665,
 'wwwsmsacubootydelious': 8349,
 'frnd': 2675,
 'bangbabes': 562,
 'order': 5122,
 'should': 6469,
 'content': 1464,
 'goto': 2908,
 'bangb': 561,
 'internetservice': 3542,
 'menu': 4438,
 'cultures': 1610,
 'module': 4576,
 'avoid': 501,
 'missunderstding': 4531,
 'wit': 8189,
 'beloved': 678,
 'ones': 5068,
 'escape': 2242,
 'fancy': 2394,
 'bridge': 885,
 'needs': 4789,
 'lager': 3906,
 'completely': 1405,
 'formclark': 2605,
 'also': 226,
 ...}

In [451]:
X_transformed=vec.transform(X)
X_transformed

<5572x8512 sparse matrix of type '<class 'numpy.int64'>'
	with 70621 stored elements in Compressed Sparse Row format>

In [452]:

vec = CountVectorizer(stop_words='english' )
vec.fit(X)
vec.vocabulary_

{'jurong': 3613,
 'point': 5312,
 'crazy': 1500,
 'available': 457,
 'bugis': 896,
 'great': 2841,
 'world': 7993,
 'la': 3765,
 'buffet': 894,
 'cine': 1220,
 'got': 2802,
 'amore': 229,
 'wat': 7763,
 'ok': 4875,
 'lar': 3801,
 'joking': 3581,
 'wif': 7887,
 'oni': 4906,
 'free': 2541,
 'entry': 2144,
 'wkly': 7944,
 'comp': 1335,
 'win': 7901,
 'fa': 2272,
 'cup': 1556,
 'final': 2394,
 'tkts': 7223,
 'st': 6639,
 'text': 7066,
 'receive': 5712,
 'questionstd': 5605,
 'txt': 7424,
 'ratetcs': 5658,
 'apply': 311,
 'overs': 5005,
 'dun': 2005,
 'say': 6060,
 'early': 2025,
 'hor': 3166,
 'nah': 4587,
 'dont': 1916,
 'think': 7137,
 'goes': 2758,
 'usf': 7569,
 'lives': 3965,
 'freemsg': 2549,
 'hey': 3064,
 'darling': 1619,
 'weeks': 7818,
 'word': 7979,
 'id': 3282,
 'like': 3915,
 'fun': 2610,
 'tb': 6994,
 'xxx': 8121,
 'std': 6685,
 'chgs': 1165,
 'send': 6150,
 'rcv': 5669,
 'brother': 863,
 'speak': 6554,
 'treat': 7353,
 'aids': 158,
 'patent': 5103,
 'request': 5823,
 'melle': 4282,
 'oru': 4971,
 'minnaminunginte': 4363,
 'nurungu': 4808,
 'vettam': 7633,
 'set': 6179,
 'callertune': 963,
 'callers': 962,
 'press': 5442,
 'copy': 1441,
 'friends': 2573,
 'winner': 7913,
 'valued': 7603,
 'network': 4660,
 'customer': 1568,
 'selected': 6136,
 'receivea': 5713,
 'prize': 5476,
 'reward': 5882,
 'claim': 1226,
 'code': 1286,
 'kl': 3726,
 'valid': 7599,
 'hours': 3185,
 'mobile': 4423,
 'months': 4468,
 'entitled': 2141,
 'update': 7528,
 'latest': 3817,
 'colour': 1309,
 'mobiles': 4424,
 'camera': 989,
 'im': 3311,
 'gonna': 2775,
 'home': 3133,
 'soon': 6504,
 'want': 7743,
 'talk': 6960,
 'stuff': 6784,
 'anymore': 281,
 'tonight': 7279,
 'ive': 3496,
 'cried': 1518,
 'today': 7240,
 'chances': 1103,
 'cash': 1046,
 'pounds': 5377,
 'csh': 1535,
 'cost': 1454,
 'pday': 5128,
 'days': 1645,
 'tsandcs': 7388,
 'reply': 5815,
 'hl': 3100,
 'info': 3371,
 'urgent': 7549,
 'won': 7963,
 'week': 7813,
 'membership': 4288,
 'jackpot': 3505,
 'tc': 6996,
 'wwwdbuknet': 8067,
 'lccltd': 3836,
 'pobox': 5295,
 'ldnwarw': 3838,
 'searching': 6107,
 'right': 5894,
 'words': 7982,
 'thank': 7084,
 'breather': 832,
 'promise': 5515,
 'wont': 7970,
 'help': 3037,
 'granted': 2830,
 'fulfil': 2607,
 'wonderful': 7967,
 'blessing': 715,
 'times': 7199,
 'date': 1628,
 'sunday': 6850,
 'xxxmobilemovieclub': 8122,
 'use': 7563,
 'credit': 1508,
 'click': 1248,
 'wap': 7748,
 'link': 3938,
 'message': 4313,
 'httpwap': 3212,
 'xxxmobilemovieclubcomnqjkgighjjgcbl': 8123,
 'oh': 4868,
 'kim': 3693,
 'watching': 7768,
 'eh': 2073,
 'remember': 5782,
 'spell': 6570,
 'yes': 8162,
 'did': 1792,
 'naughty': 4616,
 'make': 4156,
 'wet': 7854,
 'fine': 2401,
 'thats': 7098,
 'way': 7780,
 'feel': 2349,
 'gota': 2803,
 'england': 2124,
 'macedonia': 4120,
 'miss': 4383,
 'goalsteam': 2749,
 'news': 4672,
 'ur': 7546,
 'national': 4609,
 'team': 7012,
 'trywales': 7386,
 'scotland': 6086,
 'poboxoxwwq': 5300,
 'seriously': 6172,
 'going': 2763,
 'try': 7383,
 'ha': 2914,
 'pay': 5116,
 'da': 1584,
 'stock': 6713,
 'comin': 1325,
 'aft': 123,
 'finish': 2407,
 'lunch': 4095,
 'str': 6742,
 'lor': 4022,
 'ard': 338,
 'smth': 6448,
 'ffffffffff': 2366,
 'alright': 210,
 'meet': 4267,
 'sooner': 6506,
 'just': 3615,
 'forced': 2495,
 'eat': 2038,
 'slice': 6398,
 'really': 5693,
 'hungry': 3239,
 'tho': 7154,
 'sucks': 6822,
 'mark': 4192,
 'getting': 2704,
 'worried': 7999,
 'knows': 3737,
 'sick': 6308,
 'turn': 7409,
 'pizza': 5238,
 'lol': 3999,
 'convincing': 1427,
 'catch': 1058,
 'bus': 916,
 'frying': 2595,
 'egg': 2068,
 'tea': 7006,
 'eating': 2041,
 'moms': 4447,
 'left': 3858,
 'dinner': 1824,
 'love': 4047,
 'amp': 230,
 'packing': 5027,
 'car': 1013,
 'ill': 3307,
 'let': 3882,
 'know': 3733,
 'theres': 7121,
 'room': 5938,
 'ahhh': 149,
 'work': 7985,
 'vaguely': 7594,
 'does': 1887,
 'wait': 7714,
 'clear': 1242,
 'sure': 6878,
 'sarcastic': 6038,
 'doesnt': 1889,
 'live': 3961,
 'yeah': 8149,
 'apologetic': 298,
 'fallen': 2299,
 'actin': 61,
 'spoilt': 6598,
 'child': 1181,
 'caught': 1062,
 'till': 7194,
 'doing': 1900,
 'badly': 506,
 'cheers': 1147,
 'tell': 7031,
 'fear': 2341,
 'fainting': 2289,
 'housework': 3190,
 'quick': 5606,
 'cuppa': 1558,
 'thanks': 7085,
 'subscription': 6811,
 'ringtone': 5903,
 'uk': 7455,
 'charged': 1115,
 'month': 4464,
 'confirm': 1382,
 'replying': 5817,
 'yup': 8227,
 'look': 4010,
 'timings': 7206,
 'msg': 4517,
 'xuhui': 8117,
 'learn': 3848,
 'nd': 4622,
 'lesson': 3880,
 'oops': 4923,
 'roommates': 5941,
 'letter': 3884,
 'decide': 1682,
 'hello': 3030,
 'hows': 3196,
 'saturday': 6052,
 'texting': 7073,
 'youd': 8191,
 'decided': 1683,
 'tomo': 7264,
 'trying': 7385,
 'invite': 3434,
 'pls': 5274,
 'ahead': 147,
 'watts': 7777,
 'wanted': 7745,
 'weekend': 7815,
 'abiola': 14,
 'forget': 2501,
 'need': 4635,
 'crave': 1497,
 'sweet': 6908,
 'arabian': 335,
 'steed': 6692,
 'mmmmmm': 4413,
 'yummy': 8222,
 'rodger': 5927,
 'burns': 913,
 'tried': 7362,
 'sms': 6443,
 'nokia': 4732,
 'camcorder': 987,
 'delivery': 1721,
 'tomorrow': 7267,
 'seeing': 6125,
 'hope': 3157,
 'man': 4166,
 'endowed': 2114,
 'ltgt': 4080,
 'inches': 3340,
 'callsmessagesmissed': 979,
 'calls': 978,
 'didnt': 1794,
 'hep': 3046,
 'immunisation': 3323,
 'nigeria': 4689,
 'fair': 2290,
 'hopefully': 3161,
 'tyler': 7435,
 'maybe': 4240,
 'ask': 388,
 'bit': 689,
 'stubborn': 6773,
 'hospital': 3173,
 'kept': 3664,
 'telling': 7032,
 'weak': 7787,
 'sucker': 6820,
 'hospitals': 3174,
 'suckers': 6821,
 'thinked': 7138,
 'time': 7196,
 'saw': 6059,
 'class': 1234,
 'gram': 2822,
 'usually': 7580,
 'runs': 5984,
 'half': 2931,
 'eighth': 2075,
 'smarter': 6421,
 'gets': 2700,
 'second': 6111,
 'fyi': 2625,
 'ride': 5893,
 'morning': 4478,
 'hes': 3059,
 'crashing': 1496,
 'place': 5240,
 'wow': 8017,
 'realized': 5691,
 'embarassed': 2096,
 'accomodations': 42,
 'thought': 7158,
 'liked': 3916,
 'best': 645,
 'happy': 2966,
 'cave': 1066,
 'sorry': 6516,
 'offered': 4849,
 'embarassing': 2097,
 'ac': 28,
 'sptv': 6621,
 'new': 4667,
 'jersey': 3548,
 'devils': 1772,
 'detroit': 1766,
 'red': 5736,
 'wings': 7911,
 'play': 5256,
 'ice': 3277,
 'hockey': 3117,
 'correct': 1446,
 'incorrect': 3351,
 'end': 2110,
 'mallika': 4165,
 'sherawat': 6232,
 'yesterday': 8172,
 'lturlgt': 4084,
 'congrats': 1389,
 'year': 8151,
 'special': 6556,
 'cinema': 1221,
 'pass': 5091,
 'suprman': 6876,
 'matrix': 4227,
 'starwars': 6671,
 'bxipwe': 936,
 'pm': 5283,
 'later': 3815,
 'meeting': 4270,
 'reached': 5675,
 'yesgauti': 8165,
 'sehwag': 6133,
 'odi': 4843,
 'series': 6171,
 'pick': 5208,
 'burger': 908,
 'pain': 5034,
 'killing': 3690,
 'good': 2777,
 'joke': 3576,
 'girls': 2725,
 'situation': 6359,
 'seekers': 6126,
 'checking': 1141,
 'iq': 3448,
 'took': 7285,
 'forever': 2498,
 'come': 1317,
 'double': 1929,
 'check': 1137,
 'hair': 2926,
 'dresser': 1963,
 'said': 6006,
 'wun': 8053,
 'cut': 1572,
 'short': 6272,
 'nice': 4682,
 'pleased': 5267,
 'advise': 105,
 'following': 2477,
 'recent': 5716,
 'review': 5880,
 'mob': 4421,
 'awarded': 476,
 'bonus': 758,
 'song': 6498,
 'dedicated': 1693,
 'day': 1640,
 'dedicate': 1692,
 'valuable': 7601,
 'frnds': 2582,
 'rply': 5958,
 'complimentary': 1354,
 'trip': 7363,
 'eurodisinc': 2182,
 'trav': 7345,
 'acoentry': 57,
 'dis': 1837,
 'morefrmmob': 4475,
 'shracomorsglsuplt': 6294,
 'ls': 4071,
 'aj': 169,
 'hear': 3006,
 'divorce': 1866,
 'barbie': 539,
 'comes': 1321,
 'kens': 3662,
 'plane': 5247,
 'wah': 7707,
 'lucky': 4088,
 'save': 6055,
 'money': 4452,
 'hee': 3022,
 'finished': 2409,
 'hi': 3069,
 'babe': 490,
 'wanna': 7741,
 'xx': 8118,
 'kkwhere': 3723,
 'youhow': 8194,
 'performed': 5153,
 'waiting': 7718,
 'machan': 4122,
 'cool': 1433,
 'gentleman': 2687,
 'dignity': 1814,
 'respect': 5844,
 'peoples': 5146,
 'shy': 6303,
 'pa': 5022,
 'operate': 4930,
 'looking': 4014,
 'job': 3563,
 'tas': 6978,
 'earn': 2026,
 'ah': 145,
 'stop': 6723,
 'urgnt': 7553,
 'real': 5685,
 'yo': 8182,
 'tickets': 7185,
 'jacket': 3504,
 'used': 7564,
 'multis': 4546,
 'started': 6664,
 'requests': 5824,
 'came': 988,
 'bed': 605,
 'coins': 1293,
 'factory': 2280,
 'gotta': 2808,
 'nitros': 4713,
 'ela': 2079,
 'kanoil': 3639,
 'download': 1937,
 'wen': 7837,
 'stand': 6652,
 'close': 1255,
 'youll': 8198,
 'night': 4691,
 'spent': 6575,
 'late': 3810,
 'afternoon': 125,
 'casualty': 1056,
 'means': 4254,
 'havent': 2988,
 'stuffmoro': 6788,
 'includes': 3344,
 'sheets': 6227,
 'smile': 6430,
 'pleasure': 5269,
 'trouble': 7369,
 'pours': 5379,
 'rain': 5630,
 'sum': 6842,
 'hurts': 3253,
 'becoz': 603,
 'loves': 4057,
 'smiling': 6434,
 'service': 6175,
 'representative': 5821,
 'ampm': 232,
 'guaranteed': 2882,
 'planning': 5252,
 'buy': 927,
 'lido': 3897,
 'collected': 1302,
 'simply': 6331,
 'password': 5099,
 'mix': 4403,
 'verify': 7629,
 'usher': 7571,
 'britney': 853,
 'fml': 2467,
 'telugu': 7037,
 'moviewat': 4504,
 'abt': 23,
 'loads': 3976,
 'loans': 3978,
 'wk': 7940,
 'hols': 3131,
 'run': 5981,
 'forgot': 2506,
 'hairdressers': 2928,
 'appointment': 314,
 'shower': 6287,
 'cause': 1063,
 'prob': 5482,
 'ham': 2937,
 'okay': 4876,
 'price': 5455,
 'long': 4006,
 'legal': 3861,
 'ave': 463,
 'ams': 235,
 'gone': 2772,
 'driving': 1972,
 'test': 7060,
 'youre': 8204,
 'mean': 4250,
 'guess': 2890,
 'gave': 2658,
 'boston': 780,
 'men': 4293,
 'changed': 1105,
 'search': 6106,
 'location': 3981,
 'nyc': 4818,
 'cuz': 1579,
 'signin': 6319,
 'page': 5030,
 'says': 6064,
 'umma': 7464,
 'life': 3900,
 'vava': 7615,
 'lot': 4032,
 'dear': 1664,
 'wishes': 7926,
 'birthday': 687,
 'making': 4160,
 'truly': 7377,
 'memorable': 4290,
 'aight': 160,
 'hit': 3091,
 'ip': 3442,
 'address': 80,
 'considering': 1400,
 'computer': 1361,
 'isnt': 3467,
 'minecraft': 4358,
 'server': 6174,
 'grumpy': 2874,
 'old': 4893,
 'people': 5145,
 'mom': 4444,
 'better': 652,
 'lying': 4111,
 'jokes': 3578,
 'worry': 8002,
 'busy': 921,
 'plural': 5279,
 'noun': 4771,
 'research': 5830,
 'dinnermsg': 1825,
 'cos': 1452,
 'things': 7136,
 'scared': 6071,
 'mah': 4143,
 'loud': 4042,
 'gent': 2685,
 'contact': 1405,
 'weekends': 7816,
 'draw': 1951,
 'shows': 6293,
 'hrs': 3203,
 'ppm': 5387,
 'wa': 7703,
 'openin': 4927,
 'sentence': 6163,
 'formal': 2509,
 'juz': 3619,
 'tt': 7394,
 'eatin': 2040,
 'puttin': 5582,
 'weighthaha': 7823,
 'anythin': 285,
 'happened': 2958,
 'entered': 2134,
 'cabin': 941,
 'bday': 590,
 'boss': 779,
 'felt': 2358,
 'askd': 389,
 'invited': 3435,
 'apartment': 292,
 'went': 7840,
 'specially': 6561,
 'holiday': 3127,
 'flights': 2444,
 'operator': 4931,
 'pmin': 5285,
 'goodo': 2791,
 'friday': 2566,
 'eggpotato': 2069,
 'ratio': 5659,
 'tortilla': 7303,
 'needed': 4637,
 'hmmmy': 3113,
 'uncle': 7471,
 'informed': 3375,
 'paying': 5121,
 'school': 6077,
 'directly': 1831,
 'food': 2484,
 'private': 5473,
 'account': 46,
 'statement': 6674,
 'unredeemed': 7514,
 'points': 5313,
 'identifier': 3289,
 'expires': 2251,
 'caller': 961,
 'landline': 3788,
 'boxwrc': 800,
 'applespairsall': 309,
 'malarky': 4162,
 'todays': 7246,
 'voda': 7681,
 'numbers': 4804,
 'ending': 2112,
 'award': 475,
 'match': 4215,
 'quoting': 5618,
 'standard': 6653,
 'rates': 5657,
 'app': 302,
 'sao': 6032,
 'mu': 4535,
 'predict': 5417,
 'll': 3969,
 'buying': 930,
 'knowyetunde': 3740,
 'sent': 6161,
 'bother': 782,
 'sending': 6153,
 'involve': 3439,
 'shouldnt': 6281,
 'imposed': 3329,
 'apologise': 299,
 'girl': 2721,
 'del': 1711,
 'bak': 515,
 'lucyxx': 4092,
 'kkhow': 3717,
 'tmorrowpls': 7228,
 'accomodate': 41,
 'answer': 269,
 'question': 5602,
 'sunshine': 6857,
 'quiz': 5613,
 'sony': 6501,
 'dvd': 2014,
 'player': 5258,
 'country': 1470,
 'algarve': 189,
 'ansr': 268,
 'sptyrone': 6622,
 'laid': 3779,
 'dogging': 1894,
 'locations': 3982,
 'direct': 1830,
 'join': 3571,
 'uks': 7458,
 'largest': 3805,
 'bt': 879,
 'txting': 7429,
 'gravel': 2835,
 'nt': 4792,
 'eca': 2043,
 'pmsgp': 5288,
 'haf': 2920,
 'msn': 4528,
 'yijuehotmailcom': 8179,
 'rooms': 5942,
 'befor': 616,
 'activities': 67,
 'msgs': 4521,
 'chat': 1127,
 'svc': 6894,
 'hardcore': 2968,
 'services': 6176,
 'age': 132,
 'yr': 8217,
 'lazy': 3834,
 'type': 7437,
 'lect': 3855,
 'pouch': 5374,
 'sir': 6345,
 'mail': 4147,
 'swt': 6923,
 'nver': 4813,
 'tired': 7209,
 'little': 3960,
 'lovable': 4046,
 'persons': 5170,
 'cozsomtimes': 1484,
 'occupy': 4835,
 'biggest': 669,
 'hearts': 3014,
 'gud': 2884,
 'ni': 4680,
 'open': 4924,
 'ya': 8133,
 'dot': 1928,
 'whats': 7859,
 'staff': 6643,
 'taking': 6957,
 'replied': 5813,
 'randy': 5650,
 'sexy': 6191,
 'female': 2359,
 'local': 3980,
 'luv': 4101,
 'netcollex': 4656,
 'ummmawill': 7465,
 'inour': 3392,
 'begin': 621,
 'qatar': 5589,
 'pray': 5409,
 'hard': 2967,
 'ki': 3678,
 'deleted': 1715,
 'sindu': 6335,
 'birla': 683,
 'soft': 6470,
 'wine': 7909,
 'flowing': 2458,
 'nevering': 4664,
 'thk': 7146,
 'plaza': 5265,
 'typical': 7440,
 'dirt': 1834,
 'floor': 2452,
 'windows': 7906,
 'shirt': 6246,
 'mouth': 4499,
 'dream': 1955,
 'chores': 1207,
 'joy': 3593,
 'lots': 4035,
 'tv': 7414,
 'exist': 2234,
 'hail': 2925,
 'mist': 4394,
 'aaooooright': 3,
 'leaving': 3854,
 'house': 3186,
 'interview': 3421,
 'boy': 801,
 'meare': 4256,
 'missing': 4387,
 'annoncement': 260,
 'years': 8152,
 'arrange': 364,
 'safe': 6001,
 'envy': 2148,
 'sees': 6130,
 'parentsi': 5070,
 'hand': 2940,
 'excited': 2222,
 'spend': 6573,
 'bootydelious': 771,
 'inviting': 3436,
 'friend': 2571,
 'wwwsmsacubootydelious': 8087,
 'frnd': 2581,
 'bangbabes': 529,
 'order': 4955,
 'content': 1409,
 'goto': 2807,
 'bangb': 528,
 'internetservice': 3420,
 'menu': 4301,
 'cultures': 1552,
 'module': 4437,
 'avoid': 469,
 'missunderstding': 4392,
 'wit': 7931,
 'beloved': 636,
 'ones': 4904,
 'escape': 2167,
 'fancy': 2311,
 'bridge': 837,
 'needs': 4641,
 'lager': 3778,
 'completely': 1350,
 'formclark': 2513,
 'utter': 7582,
 'waste': 7760,
 'axis': 483,
 'bank': 531,
 'hmmm': 3107,
 'hop': 3156,
 'muz': 4571,
 'discuss': 1850,
 'liao': 3889,
 'coming': 1326,
 'bloody': 730,
 'hell': 3028,
 'believe': 627,
 'surname': 6884,
 'mr': 4509,
 'clue': 1268,
 'spanish': 6548,
 'begins': 622,
 'bath': 562,
 'goodfine': 2781,
 'youve': 8211,
 'carlos': 1033,
 'mall': 4164,
 'turns': 7412,
 'staying': 6682,
 'til': 7193,
 'smoke': 6437,
 'worth': 8008,
 'log': 3988,
 'spoke': 6599,
 'maneesha': 4176,
 'wed': 7804,
 'satisfied': 6047,
 'experience': 2245,
 'toll': 7260,
 'lifted': 3909,
 'hopes': 3163,
 'offer': 4848,
 'especially': 2170,
 'approaches': 318,
 'studying': 6782,
 'anyways': 289,
 'gr': 2817,
 'trust': 7379,
 'guys': 2906,
 'greatbye': 2843,
 'handsome': 2946,
 'finding': 2399,
 'working': 7989,
 'net': 4655,
 'mummy': 4550,
 'wheres': 7870,
 'boytoy': 806,
 'haha': 2921,
 'awesome': 478,
 'minute': 4372,
 'freephone': 2553,
 'xmas': 8111,
 'radio': 5623,
 'jus': 3614,
 'bathe': 563,
 'sis': 6350,
 'using': 7572,
 'finishes': 2410,
 'unique': 7499,
 'th': 7080,
 'august': 442,
 'wwwareyouuniquecouk': 8056,
 'joined': 3572,
 'league': 3846,
 'touch': 7312,
 'deal': 1657,
 'personal': 5165,
 'finally': 2396,
 'completed': 1349,
 'course': 1476,
 'suggest': 6835,
 'stays': 6683,
 'able': 16,
 'ors': 4968,
 'stool': 6722,
 'settled': 6183,
 'wishin': 7927,
 'mrng': 4511,
 'hav': 2985,
 'story': 6741,
 'hamster': 2939,
 'dead': 1655,
 'tmr': 7229,
 'orchard': 4954,
 'mrt': 4513,
 'kate': 3645,
 'evening': 2190,
 'babyjontet': 497,
 'enc': 2109,
 'bucks': 887,
 'darlin': 1618,
 'college': 1306,
 'refilled': 5747,
 'successfully': 6819,
 'inr': 3395,
 'ltdecimalgt': 4076,
 'keralacircle': 3666,
 'prepaid': 5428,
 'balance': 518,
 'rs': 5961,
 'transaction': 7334,
 'kr': 3753,
 'goodmorning': 2785,
 'sleeping': 6390,
 'ga': 2626,
 'alter': 215,
 'dat': 1626,
 'ericsson': 2154,
 'oso': 4974,
 'oredi': 4958,
 'dats': 1634,
 'straight': 6743,
 'dogg': 1892,
 'connection': 1393,
 'refund': 5752,
 'shoot': 6263,
 'big': 667,
 'ready': 5683,
 'bruv': 874,
 'break': 824,
 'rewarding': 5883,
 'semester': 6146,
 'kkgoodstudy': 3716,
 'noe': 4722,
 'leh': 3864,
 'sounds': 6532,
 'heading': 2998,
 'prediction': 5420,
 'slept': 6397,
 'past': 5101,
 'nights': 4695,
 'easy': 2037,
 'ahsen': 154,
 'exam': 2218,
 'march': 4188,
 'gt': 2878,
 'atm': 418,
 'register': 5759,
 'os': 4972,
 'called': 960,
 'ubandu': 7442,
 'installing': 3404,
 'diskyou': 1853,
 'important': 3327,
 'files': 2385,
 'repair': 5805,
 'shop': 6264,
 ...}

In [453]:

print(vec.get_feature_names_out())
print(len(vec.get_feature_names_out()))

['aa' 'aah' 'aaniye' ... 'zouk' 'zs' 'zyada']
8245

In [454]:
X_transformed=vec.transform(X)
X_transformed

<5572x8245 sparse matrix of type '<class 'numpy.int64'>'
	with 40985 stored elements in Compressed Sparse Row format>

**Having problem in this,when i print X before converting toarray() it prints the values but after that it converts all to zero,thats why not getting accuracy.**

In [455]:



X=X_transformed.todense()
X

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])

In [456]:
pd.DataFrame(X, columns=vec.get_feature_names_out())

,aa,aah,aaniye,aaooooright,aathilove,aathiwhere,ab,abbey,abdomen,abeg,...,zeros,zf,zhong,zindgi,zoe,zogtorius,zoom,zouk,zs,zyada
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5567,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5568,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5569,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5570,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5571,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [457]:
test_docs = pd.read_csv('Spam_test.csv')
test_docs

    v1                                   v2
0  ham  Please come.Lets do our Assignment.
1  ham        Okay we will meet there soon.

In [458]:
test_numpy_array = test_docs.values
X_test = test_numpy_array[:,0]
Y_test = test_numpy_array[:,1]

Y_test = Y_test.astype('str')
print("X_test")
print(X_test)
print("Y_test")
print(Y_test)

X_test
['ham' 'ham']
Y_test
['Please come.Lets do our Assignment.' 'Okay we will meet there soon.']

In [459]:
X_test_transformed=vec.transform(X_test)
X_test_transformed

<2x8245 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Row format>

**Having problem in this,when i print X before converting toarray() it prints the values but after that it converts all to zero,thats why not getting accuracy.**

In [460]:
X_test=X_test_transformed.toarray()
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [461]:
from sklearn.metrics import accuracy_score

# Assuming you have the predicted labels in y_pred and the actual labels in y_true
accuracy = accuracy_score(Y_test, Y_test)
print("Accuracy:", accuracy)

Accuracy: 1.0